### ISSUE TITLE
Weekly Scrum - Tuesday, April 04, 2022

### ISSUE THREAD

**Issue by Calacorm** [NicolasDuciaume/SYSC4806_Web_App#79]
Record of Scrum Meeting:

What I Did:

What I am doing next:

Blockers:

**Comment by Calacorm** [comment]
What I did:
- Finished UserRoles feature and integrated with Nick's new login feature
- We can now visit the view_users.html page of admin portal and see all users in a tabular system.
- - You can click a button to toggle the role of a user.  NO_ROLE -> FREE_USER -> PAID_USER -> FREE_USER... (repeats)
- - This is arbitrary behavior and acts as a proof of concept we can change the roles of users, it uses a special endpoint that checks the role type and determines with a utility method if it can upgrade or not.
- - The table updates every second, so the role may not update instantly, it is based on server_side data and I couldn't figure out a way to instantly update the local client side value of the table. Still need to learn how to use datatables.js better.

What I am doing next:
- my feature contributions are done, I offer support and maybe small pull requests to fix and polish the program

Blockers:
None

**Comment by aimansharif** [comment]
Record of Scrum Meeting:

What I Did:
* Finished the Delete User Portal feature and integrated feature with main application
* Added HTML page to prompt user to confirm the deletion of the user
* Added CSS styling for the buttons and elements in the user deletion HTML page
* Added an option for user to finalize confirmation of deletion or go back to user portal page
* Added integration tests to check delete user portal functionality correctly works as expected
* Tested to check that the users are deleted successfully after confirmation of user deletion
* Tested through Admin portal to check list of users after confirmation

What I am doing next:
* The work on the main feature is done from my part
* Going to help out fixing small bugs if necessary and refactor code

Blockers:
None

**Comment by NicolasDuciaume** [comment]
What I Did:

-  Figured what had been done and needs to be done

-  Login system is functional

-  Registration is functional

-  basic test for rest controller and main controller are done

- Comments added to most methods

- Updated login to be done through ajax

-  Added system to check for already existing username

- changed checking system to be done through ajax

- Added alert for wrong username and password

- Added alert for username already used

-  Update the CSS for the login page

- Update the CSS for the Registration page

-  Change registration/creation of user to be done directly through ajax

- Add special requirements for password

-  Add alert for missing requirement in password

-  Update comments

-  Update Test

- Add system to set role when creating an account

- Switch admin check to be done in javascript through rest calls

- Switch to passing user information through content body of rest call

What I am doing next:
- Reviewing merge issues and converting to heroku

Blockers:
- Encryption and decryption was an issue as I had only experience with these concepts in c/c++ as such I stuck with removing any identifying commands from the html page and transfer user information through the json body of the rest calls

**Comment by nazifatanzim** [comment]
Record of Scrum Meeting:

**What I Did:**

1. Reviewed PRs
2. Completed my feature (see details below)

UserPortalController:
- checks the user's role and applies restrictions accordingly
- checks if a free user has reached their "AppX" use limits upon each entry. Entry is blocked if the limit has been reached
- gets and stores the user's id
- updates "clicks" in the database as well as maintaining a hashmap to "locally" store data for every user that enters the portal

Front-End:
- updated the button in user_portal that is meant to connect the user to "AppX" so that it redirects the user to app_proxy
- added app_proxy.html - a placeholder page where the "AppX" would be integrated
- added a button in app_proxy to go back to the user_portal
- display specific messages in app_proxy based on the user's role
- updated the overall look of the front-end to be consistent with the login and registration pages

Integration Tests:
- added integration tests for all endpoints in UserPortalController
- updated integration tests in Main_Controller that were impacted by this feature

**What I am doing next:**
- wait for the 2 PRs #83 and #84 to be merged so that i can rebase my branch and resolve any merge conflicts
- merge my PR

**Blockers:**
None

**Comment by cadsilva** [comment]
Record of Scrum Meeting:

What I Did:
- Cleaned up the Admin Controller and now admin_portal endpoint shows the summary of the current user base #63 
- Made changes to the front end of the admin portal page to have navigation between the user management and Admin home page. #65 
- Added Unit tests for the Admin class and also made sure integration tests where present for the admin portal endpoint #64 

What I am doing next:
- helping in exporting the URL that is used within all of the files to an external file
- updating diagrams and READMe #47 

Blockers:
- No blockers
